### ISSUE TITLE
P2P discovery for a node outside cluster

### ISSUE THREAD

**Issue by RohitGupta027** [PegaSysEng/besu-kubernetes#49]
I have used an existing `besu-kubernetes` configuration to deploy 1 node service and 4 validators on Kubernetes cluster. Now I want to connect an external node outside of cluster as a validator to the network. Also, I have created ingress rules for besu service node to enable service ports 8546, 8547, 30303  Issue is I am unable to connect to the network. I have used enode address from the deployed network `enode://<Address>@0.0.0.0:30303` to connect external node but it won't be able to identify the IP 0.0.0.0 so I have added new rule to Ingress controller to enable port 30303 on service besu node as `<PublicIP>:80/p2p/` with that I tried to connect the external node as `enode://<Address>@<PublicIP>:80/p2p/ ` but still not connected.

How can I connect the external node to a network which is running on Kubernetes where only JSON RPC(8545), WebSockets(8547) service ports are enabled on Public IP?

**Comment by joshuafernandes** [comment]
Hello @RohitGupta027 

Enode's need to be an explicit IP rather than 0.0.0.0 interface - this needs to be the IP of your host (public if its across the net, private if its on the same physical network). 

The protocol works such that discovery needs to be enabled (30303 tcp & udp) for a new node to join - if you've only got 8545 & 8547 this will not work. The ingress setup and routes in these examples will work for calls to the chain that can be load balanced, eg: in the case of a DApp making calls to a highly available node.

With regards to connecting an external node to the network, I'd suggest using a VPN to your network first with routes specified and then connecting the node to the blockchain. Reason being it is safer to limit connections to those you trust only, and secondly your new node needs to talk to all nodes on the blockchain network. 

Hope this helps

Cheers

**Comment by RohitGupta027** [comment]
@joshuafernandes Thanks for your reply, as suggested I have added a new route/rule in ingress to enable (30303 tcp & udp) for validators service 1&2 like this. The network is exposed to public Ip on port 80 & 443.

```
      - path: /p2p1(/|$)(.*)
        backend:
          serviceName: besu-validator1
          servicePort: 30303
      - path: /p2p2(/|$)(.*)
        backend:
          serviceName: besu-validator2
          servicePort: 30303
```
Now to connect the node which is not in the same physical network, I am using this command and it is not connecting to the network. 
`besu --config-file=./config.toml --bootnodes=enode://<validator1-pubkey>@51.xxx.xx.xx:80/udp1,enode://<validator2-pubkey@51.XXX.XX.XX:80/udp2`  

I thought the above enode format is not correct, therefore I tried the below option as well.
By making all validators service of type `NodePort` from `ClusterIP` and use service IPs (10.xxx.x.9) to connect to the network but it seems to be not working as well.

**Comment by joshuafernandes** [comment]
Hi @RohitGupta027 

I think you're mixing a few concepts here, please correct me if I'm wrong and don't understand your setup. From what I gather you have:
- a k8s cluster with 4 validtors + 1 node
- bootnodes are validator1 & validator2
- you've got cluster_ip services for each validator and the node
- you've got an ingress with routes to bootnodes and the single node?
- you are trying to add a new node outside the network to your cluster

The best way to add external nodes to the cluster is via a VPN so that:
- you can control the IPs accessing your network
- any new external nodes can talk to or as many nodes as possible 

Think of the ingress controller in this case as a load balancer that can route by path/host etc - a DApp wants to make RPC calls, and uses the name/ip of the ingress for that or you need to provide which routes based on rules. Eg: the paths in the snippet '/p2p1' and so on are perfect for routing traffic in this manner as you would for microservices, but wont work for p2p

A NodePort service is an option used on dev/test setups when you don't have an ingress, load balancers etc - basically it exposes ports on the nodes directly. You can use all Nodeport services, or ingress but both in the same setup aren't needed.

The ingress setup will give you access to the nodes that you specify by routes, however Im not sure how you intend for it to contact other nodes in the network - if you are intending for this node to serve as a validator it needs to be able to talk to at least all other validators - how is this being catered to in your setup? 

With a VPN & routes on your external node, it can connects to your k8s network directly and talk to all th enodes as if it was part of the network natively. Second concern is that when you introduce external validators, watch the latency and block creation time - the more you add with long latencies, it can halt your network. This is ok (not ideal) for normal nodes, but not for validators.

Enodes are of the form: enode://public_key@ip:port where ip in this case is the service ip of the node. Think of this as an address to connect to like we do with ssh. It needs to be an IP per the spec - and 0.0.0.0 wont go anywhere - its a short form for all interfaces on a machine. I'd also advise against using paths as well - the enode format doesnt cater to this by spec. If you specify 'p2p1' and 'p2p2' as paths they need to be used in the enode. In the snippet above Im not sure if they're ever called so routes would likely go to the default route.

I would suggest that you verify that you can connect to the validators from your external node first. Check your firewall, security group rules and try and open a telnet session to <service_host>:port from the external node. Once you verify you have connectivity, you need to specify an enode in this format enode://public_key@ip:port, use the nodeport service directly here for all your nodes if you cannot get a VPN setup

Only use the ingress as an interface for RPC calls or the like

Hope this helps, this isn't an issue that belongs here as it isnt an issue with the code - If you cannot get it working ask this in  https://chat.hyperledger.org/channel/besu so the rest of the community can help

**Comment by Params10** [comment]
Hello, So I created 2 clusters on aws and gcp respecting with similar setup, 4 validatiors 2 bootnodes and 1 rpc node on aws and 1 validator on gcp. I've created a vpc and VPN tunnel connection across the cloud and all of them are up and running. My pods have their own IP as I used CNI service. But still when I try to add node as a peer using admin_addpeer API call with enode of AWS bootnode-1+internal_privateIP_30303 (I can telnet the IP and port of aws pod on my gcp instance .Still the calls says true but peer is not added. what Am I missing here ? security groups and firewalls are accepting all TCP ports and sources for both the clouds .

**Comment by joshuafernandes** [comment]
Hwllo @Params10 This isn't a simple answer but sounds like routing isn't working from one cluster to another. Assuming the ports are open I'd check the following:
- Do the CIDR blocks of both the VPC's and the cluster differ - they should not overlap. Also ensure that TCP and UDP are allowed from both VPCs in/out - you can try opening all traffic on the tunnel first and once you establish this is not the issue, then restrict as needed
- Can a VM in one VPC communicate with a VM in the other via the tunnel? 
- Can a pod in k8s do the same ie if you give it the private ip of another pod in the other VPC can it route there? For example try a nginx pod in one and try and reach it from a pod in the other cluster via the tunnel

**Comment by Params10** [comment]
Hello, Thanks for  prompt response. I haven't allowed UDP traffic, would that help. CIDR range is different and yes the VMs from different cloud can communicate via VPC as I ping the private IP and not the public one.

I will try this thing once :
Can a pod in k8s do the same ie if you give it the private ip of another pod in the other VPC can it route there? For example try a nginx pod in one and try and reach it from a pod in the other cluster via the tunnel.

**Comment by Params10** [comment]
Updates, We tried to ping a pod over the vpc and we were able to establish the connections successfully. But again when we try to connect with a peer it does not increase the number of peers or is not able to connect.

Subnet cidr ranges are: 10.1.X.X for aws 
and for GCP : 10.116.X.X 

though primary CIDR range is the same for both of them 10.X.X.X

do you think this might be overlapping?

**Comment by Params10** [comment]
Hey folks, we are running out of time. Can we get some help it's kind of an emergency.If possible can we have a meet to discuss this issue ?

**Comment by joshuafernandes** [comment]
Hello @Params10 there are several things you can do - I suspect this is a routing issue cross cluster but we don't use GCP so I cannot confirm. If you are in a hurry what I'd suggest is:
1. Keep the bulk of your setup on AWS as is with the VPN tunnel etc 
2. Spin up a VM in your GCP VPC and setup Besu there - establish that you can connect, add the peer and make it a validator
3. Then move to add it in via K8S - with k8s you have to ensure their network CIDRs are independant of the other cluster + the VPN. 
4. It is impossible to help you debug without logs etc. What happens in the logs (use DEBUG level on both sides) when you connect the peer from GCP to the AWS nodes?

**Comment by joshuafernandes** [comment]
Refer to the thread here in the besu discord channel @Params10 https://discord.com/channels/905194001349627914/1172617318845657199/1317692945742430209 

I've tested AWS to Azure peering on clusters in each cloud provider and a site to site VPN between the two

**Comment by joshuafernandes** [comment]
Also refer to https://besu.hyperledger.org/private-networks/tutorials/kubernetes/multi-cluster in the docs

**Comment by Params10** [comment]
Hello @joshuafernandes , thanks for your help so far.
We're encountering an issue with ingress-rules-besu.yaml where services exposed under paths like /rpc and /validator-1 are returning "resource not found." However, ingress-rules-monitoring.yaml is working as expected.

Our goal is to expose these services so that we can add peers from another cloud(lets say from AWS to GCP or other way around). We've configured IngressClass, specified rules for Besu nodes, and applied necessary annotations, but the routes are still inaccessible.

[ingress-nginx IngressClass.txt](https://github.com/user-attachments/files/18584293/ingress-nginx.IngressClass.txt)

**Comment by Params10** [comment]
Dear @joshuafernandes,

I hope you are doing well. Due to unavoidable circumstances, our team’s funding is at risk of being shut down this week if we are unable to establish communication across cloud-based Besu nodes using our Kubernetes cluster.

We have carefully followed the complete guide and attempted multiple setups with different projects, but the Besu Kubernetes clusters are still unable to communicate. We have also enabled verbose logging and thoroughly analyzed the logs to identify the root cause, but despite our efforts, the issue persists.

We would greatly appreciate your help in troubleshooting this problem. If possible, we kindly request a call at your earliest convenience, as resolving this issue is critical for us.

Looking forward to your response.

**Comment by joshuafernandes** [comment]
Hello @Params10 

Hope all is well. That is unfortunate to hear. I'm not as familiar with GCP as I am with AWS and Azure so am not sure how helpful I will be and also given that its already the middle of the week that leaves us with little time left. We'll see what we can do between now and Friday.

Can you confirm the following please so I understand your environment please:

1. Given the cross cloud requirement, is there an absolute need for Kubernetes? 
2. Have you attempted to use VMs and if so has that worked? 
3. If Kubernetes is a must, can you use AWS and Azure - if so you can use the tutorials verbatim and it should work? 
4. Can you connect a vm to a cluster on either side (eg: spin up the cluster in AWS and then a VM in GCP) This would be the first step as I mentioned earlier - if you can spin up a VM in the same subnet/security group etc as that of k8s and have that VM connect to the cluster does that work? I wouldn't start attempting to do cross cluster comms until this works 
5. Your last request had issues with ingress rules, did the native services work fine as is before you got to the ingresses or were you attempting to peer cross cluster comms via the ingress. If so this won't work, peering needs to be as simple and straightforward as possible as the clients broadcast their IP, not the ingress's IP as per the tutorials https://besu.hyperledger.org/private-networks/tutorials/kubernetes/multi-cluster. Please note the ingresses are more for external services ie DApps, microservices etc
6. What do the logs say - its hard to figure out what is wrong with no logs at all

Cheers

**Comment by Params10** [comment]
Thank you for responding quickly,

1. Given the cross-cloud requirement, is there an absolute need for Kubernetes?
   
       Yes, our requirement suggests that we need Kubernetes, We have tried with VMs, and that did work cross-cloud.

2.  Have you attempted to use VMs and if so has that worked?
     
       Yes, we have tried with VMs.

3. If Kubernetes is a must, can you use AWS and Azure - if so you can use the tutorials verbatim and it should work.
     
     We do not have resources available for Azure, Hence we have to do it with GCP and AWS.

4. Can you connect a vm to a cluster on either side (eg: spin up the cluster in AWS and then a VM in GCP) This would be the first step as I mentioned earlier - if you can spin up a VM in the same subnet/security group etc as that of k8s and have that VM connect to the cluster does that work? I wouldn't start attempting to do cross cluster comms until this works

    We haven't tried this yet, but we plan to test a similar setup on AWS and GCP and will update you accordingly. Could you 
    guide us on how to add peers from a cluster to a VM IP manually? We're unsure whether adding a peer API call would work in 
    this scenario.

5. Your last request had issues with ingress rules, did the native services work fine as is before you got to the ingresses or were you attempting to peer cross-cluster comms via the ingress? If so this won't work, peering needs to be as simple and straightforward as possible as the clients broadcast their IP, not the ingress's IP as per the tutorials https://besu.hyperledger.org/private-networks/tutorials/kubernetes/multi-cluster. Please note the ingresses are more for external services ie DApps, microservices etc

    Yes, we followed the instructions in this link and updated the ingress document. However, we suspect that a minor issue with 
    adding peers and encoding URLs might be causing the problem.

6.  What do the logs say - its hard to figure out what is wrong with no logs at all

      Sorry about that, let me share a chat on discord : https://discord.com/channels/905194001349627914/1172617318845657199/threads/1317692945742430209
where you can find the logs.

**Comment by joshuafernandes** [comment]
Hello @Params10 

Do **not** use the ingress for peering and please keep it simple ie do not use permissioning either until you have things working, then add that in incrementally.

Peering in general requires the enode of this form

`the_id@the_ip:the_port`  when the gossip requests are sent (see 'PING' in the trace logs) the request has the senders IP. When you put ingresses and load balancers on the front the addresses are different and you have to ensure routing works across components

```
enode://f59c0ab603377b6ec88b89d5bb41b98fc385030ab1e4b03752db6f7dab364559d92c757c13116ae6408d2d33f0138e7812eb8b696b2a22fe3332c4b5127b22a3@127.0.0.1:30303"
```

To peer a VM to a besu_node in a cluster (assuming cluster is in GCP):
- Ensure you have the security groups open on the public IP of the host - see the tutorial and you'll need to work out how to set this up on GCP
- Use CNI for networking (or equivalent in GCP) and ensure the besu flag p2p-host is an IP from the subnet ie https://github.com/Consensys/quorum-kubernetes/blob/master/helm/charts/besu-node/templates/node-statefulset.yaml#L210. Essentially what you are doing is a 1:1 besu_pod per host and binding the besu pod to the host's network interface to communicate externally.
- Ensure your VPN tunnel is working 
-  Spin up the VM in AWS and make sure you can make a request to the besu node on the cluster eg https://besu.hyperledger.org/public-networks/reference/api#admin_nodeinfo and use the ip of the pod - that should ensure connectivity is working between AWS and GCP. Then add the peer with https://besu.hyperledger.org/public-networks/reference/api#admin_addpeer
- Let the VM run and make sure the VM and the cluster are communicating happily. 
- Once this is working, follow the steps in the tutorial to get the AWS side working and use the IPs of the pod in GCP - you will probably need to put them in a configmap or the like - between clusters the DNS names won't work so you need to use the IP addresses

The process to add peers from a VM to the cluster is the same as a pod on another cluster - its just an API call. Assuming you have the networking and routing working correctly, it'll 'just' work, so to speak

Keep it simple and work up gradually, I wouldn't complicate things right from the get go until you've verified the basic setup works

Let me know how that goes.

Cheers,
Josh

**Comment by Params10** [comment]
Thank you for your prompt response.

I will definitely give this method a try. I would have put in extra effort and dedicated more time to this approach, but I was wondering if you could set up a call due to unavoidable circumstances and the impending deadline. The deadline is very close, and we would greatly appreciate your help as soon as possible.

Looking forward to your response.

**Comment by joshuafernandes** [comment]
Hi @Params10 

Im not familiar with GCP so not sure how much help I could be. Realistically unless the VPN connection between the two is working properly the rest of the setup won't work - the only other option is to expose thing publicly via the internet. 

Im based in Australia, GMT+10 - I could possibly do a quick half hr call at most maybe tomorrow depending on priorities between either 7-8am AEST, or 0830 - 0900 AEST - not sure if that works for you depending on your time zone. 

Given your time constraints I'd focus on:
1. Getting the VPN working and tested 
2. Make an RPC request from a VM in AWS to your validators in GCP and then add the VM as a peer
3. Setup the AWS cluster as per the tutorial. If you have step2 working then 3 should also work
4. Setup an RPC node on either end and use the ingress for normal RPC calls. Peer to peer comms between besu nodes should be direct without ingresses / load balancers etc etc - keep it simple and route straight from one to another via the VPN

Cheers

**Comment by Params10** [comment]
Hey @joshuafernandes ,

We are based in United States, and Any time works for us . 

We will try to do the things that you have mentioned before our meeting if possible to keep you posted on this.

Thank you for your help,

Cheers,
Param

**Comment by Params10** [comment]
Hey @joshuafernandes , 

We tried to connect VM with kubernates clusters, you can see that it tries to connect to gcp clusters nodes with IP from range 10.180.X.X they are not able to connect to peer can you let me know what can be the issue ?  Incase you are available can you setup a call anytime soon .

![Image](https://github.com/user-attachments/assets/8c56f1de-b9e6-4604-80c2-8a01016d5f5b)

**Comment by joshuafernandes** [comment]
Hello @Params10 

Thanks for that. That looks normal - those messages would be from https://github.com/hyperledger/besu/pull/6225 - its responding to the Host IP directly. 

What email address do I use to send a zoom meeting invite to? I can meet at present for about the next half hour or so

Cheers

**Comment by Params10** [comment]
Hello @joshuafernandes ,
Can you send invite to pshah91@asu.edu and psing161@asu.edu . 

Cheers

**Comment by joshuafernandes** [comment]
> Hello [@joshuafernandes](https://github.com/joshuafernandes) , Can you send invite to [pshah91@asu.edu](mailto:pshah91@asu.edu) and [psing161@asu.edu](mailto:psing161@asu.edu) .
> 
> Cheers

Done, you should receive a request momentarily
