### ISSUE TITLE
How to deploy a smart contract on minikube?

### ISSUE THREAD

**Issue by yehia67** [PegaSysEng/besu-kubernetes#57]
Hello,
I am trying to deploy a smart contract using truffle. So I created a network on `truffle-config`.
```
k8s: {
      provider: () => new PrivateKeyProvider(privateKey, "http://172.18.0.10:8545"),
      gas: "0x1ffffffffffffe",
      gasPrice: 0,
      network_id: "*"
    },
```
But it doesn't work. I know to interact with the Blockchain I need to `minikube ssh`.  How to deploy a contract with truffle? 
Thanks In Advance

**Comment by yehia67** [comment]
Should I install truffle and clone the project repository inside minikube(after ` minikube ssh`) to deploy the contract?

**Comment by joshuafernandes** [comment]
Hello @yehia67 

I'd suggest looking at some tutorials of kubernetes networking works eg: https://itnext.io/an-illustrated-guide-to-kubernetes-networking-part-1-d1ede3322727 

Basically you need to be able to connect to your rpc endpoint from wherever you are running the contract from (eg IDE, local host etc). 

If your nodes are on minikube the only way in from outside the cluster is : 
- a nodeport service like the monitoring examples, bear in mind that a node ports services' port range is 30000-32767 so 8545 wont work and you need to map it to 30045 for example. Look at the grafana service in the examples for reference
- ingress controllers 
Both of the above use the minikube IP address - get this by doing `minikube ip`. So you config should be : 
```   provider: () => new PrivateKeyProvider(privateKey, "http://<minikube_ip>:<port>"), ... ```

The above will work if your contract is being run from IDE or the like (outside the nodes)

If you deploy your contract as another pod inside the cluster what you've got will work perfectly fine - suggest using the node service ip as an env var rather than a fixed ip - in the event the pod goes down the contract wont work.

Hope this helps
